version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  forgetful:
    image: forgetful:latest
    ports:
      - 8080:8080
    environment:
      - DBURI=postgresql://postgres:postgres@db/postgres
volumes:
  db:
    driver: local
